# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: pdsGmbH.pdsSoftwareClient
PackageVersion: 12.2.2
PackageLocale: de-DE
Publisher: pds GmbH
PublisherUrl: https://www.pds.de/
PublisherSupportUrl: https://www.pds.de/
PrivacyUrl: https://www.pds.de/Datenschutz
Author: pds GmbH
PackageName: pds Software Client
License: MIT-Lizenz
Copyright: Copyright (C) 2024 pds GmbH
ShortDescription: pds Software Client Installer
Description: Installiert den pds Software Client für die Anwendung pds Software.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
